### ISSUE TITLE
ERR_SOCKET_DGRAM_NOT_RUNNING

### ISSUE THREAD

**Issue by bekaxe** [estbeetoo/node-red-contrib-knx#32]
Hi, 

my installation runs fine for a while and the connection to the KNX Bus works without problems. After a while the connection drops and the following error is displayed: 

```
groupAddrSend error: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:919:11)
    at Socket.send (dgram.js:643:3)
    at KnxSenderTunneling.SendData (/home/pi/.node-red/node_modules/knx.js/src/KnxSenderTunneling.js:43:21)
    at KnxSenderTunneling.KnxSender.Action (/home/pi/.node-red/node_modules/knx.js/src/KnxSender.js:9:10)
    at KnxConnectionTunneling.KnxConnection.Action (/home/pi/.node-red/node_modules/knx.js/src/KnxConnection.js:120:20)     
    at /home/pi/.node-red/node_modules/node-red-contrib-knx/knx.js:310:37
    at KnxControllerNode.initializeKnxConnection (/home/pi/.node-red/node_modules/node-red-contrib-knx/knx.js:37:21)
    at KnxOut.groupAddrSend (/home/pi/.node-red/node_modules/node-red-contrib-knx/knx.js:292:27)
    at KnxOut._inputCallback (/home/pi/.node-red/node_modules/node-red-contrib-knx/knx.js:107:18)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26 
{   code: 'ERR_SOCKET_DGRAM_NOT_RUNNING' }
```

**Comment by jamel-86** [comment]
I made this pull request, maaybe it will help you:

https://github.com/estbeetoo/node-red-contrib-knx/pull/35
